//! A list filters and sorts as astrid-web's list view does — where the clients agree.
//!
//! `contracts/fixtures/filters.json` is generated by running the three pure functions
//! `hooks/useFilterState.ts` calls — `applyDateFilter` (behind the hook's own `overdue` guard),
//! `shouldShowCompletedByFilter` and `sortTasksForList` — over a case table, at a pinned clock in
//! UTC. Each case here runs through the core at the same instant with a zero offset.
//!
//! Disputed cases are the ones where the core follows iOS and web has not moved (D7, D33–D36).
//! Each entry must still disagree with web somewhere, and the core's iOS answer is asserted.

mod common;

use std::collections::BTreeMap;

use astrid_rules::filters::recently_completed::{should_show_completed, should_show_open};
use astrid_rules::filters::{matches_due_date, sort_by_setting};
use astrid_rules::model::{date, RecentlyCompletedWindow, Task};
use chrono::{DateTime, FixedOffset, Utc};
use serde_json::Value;

const FIXTURE: &str = include_str!("../../../contracts/fixtures/filters.json");

struct Fixture {
    raw: Value,
    now: DateTime<Utc>,
    due_tasks: BTreeMap<String, Task>,
    completion_tasks: BTreeMap<String, Task>,
    windows: BTreeMap<String, Option<RecentlyCompletedWindow>>,
    sort_tasks: Vec<Task>,
}

fn utc() -> FixedOffset {
    FixedOffset::east_opt(0).expect("UTC")
}

fn table(value: &Value) -> BTreeMap<String, Task> {
    value
        .as_array()
        .expect("a task table")
        .iter()
        .map(|t| {
            let task: Task = serde_json::from_value(t.clone()).expect("a task decodes");
            (task.id.clone(), task)
        })
        .collect()
}

fn load() -> Fixture {
    let raw: Value = serde_json::from_str(FIXTURE).expect("the fixture parses");
    Fixture {
        now: date::parse(raw["now"].as_str().unwrap()).expect("now"),
        due_tasks: table(&raw["dueTasks"]),
        completion_tasks: table(&raw["completionTasks"]),
        windows: raw["windows"]
            .as_object()
            .unwrap()
            .iter()
            .map(|(name, w)| {
                (
                    name.clone(),
                    serde_json::from_value(w.clone()).expect("a window decodes"),
                )
            })
            .collect(),
        sort_tasks: serde_json::from_value(raw["sortTasks"].clone()).expect("sort tasks"),
        raw,
    }
}

/// The core's answer to one case, in the fixture's terms.
fn answer(f: &Fixture, case: &Value) -> Value {
    let id = case["id"].as_str().unwrap();
    if id.starts_with("due/") {
        let task = &f.due_tasks[case["task"].as_str().unwrap()];
        let filter = case["filter"].as_str().unwrap();
        Value::Bool(matches_due_date(task, Some(filter), f.now, utc()))
    } else if id.starts_with("completion/") {
        let task = &f.completion_tasks[case["task"].as_str().unwrap()];
        let mode = case["mode"].as_str();
        let now = date::parse(case["now"].as_str().unwrap()).expect("now");
        let window = f.windows[case["window"].as_str().unwrap()].as_ref();
        Value::Bool(if task.completed {
            should_show_completed(mode, task.completed_at, task.updated_at, window, now, utc())
        } else {
            should_show_open(mode)
        })
    } else if id.starts_with("sort/") {
        let mut tasks = f.sort_tasks.clone();
        let order: Option<Vec<String>> = serde_json::from_value(case["manualOrder"].clone()).ok();
        sort_by_setting(&mut tasks, case["sortBy"].as_str(), order.as_deref());
        Value::from(tasks.into_iter().map(|t| t.id).collect::<Vec<_>>())
    } else {
        panic!("unknown case kind {id}")
    }
}

#[test]
fn every_undisputed_case_answers_as_web_does() {
    let f = load();
    let cases = f.raw["cases"].as_array().unwrap();
    assert!(cases.len() >= 500);
    let failures: Vec<String> = cases
        .iter()
        .filter_map(|case| {
            let ours = answer(&f, case);
            (ours != case["shown"])
                .then(|| format!("{}: web {}, core {ours}", case["id"], case["shown"]))
        })
        .collect();
    common::no_failures("filters.json", &failures);
}

#[test]
fn each_disputed_entry_still_disagrees_with_web() {
    let f = load();
    let answered: Vec<common::Answered> = f.raw["disputed"]
        .as_array()
        .unwrap()
        .iter()
        .map(|case| common::Answered {
            entry: case["entry"].as_str().unwrap().to_string(),
            id: case["id"].as_str().unwrap().to_string(),
            agrees_with_web: answer(&f, case) == case["shown"],
        })
        .collect();
    common::each_dispute_still_disagrees(
        "filters.json",
        &common::declared(&f.raw["disputes"]),
        &answered,
    );
}

fn disputed<'a>(f: &'a Fixture, entry: &'a str) -> impl Iterator<Item = &'a Value> + 'a {
    f.raw["disputed"]
        .as_array()
        .unwrap()
        .iter()
        .filter(move |c| c["entry"] == entry)
}

/// D7: an unrecognised due-date filter keeps dated tasks and drops undated ones on iOS
/// (`applyListDueDateFilter`'s guard) and here; web keeps both.
#[test]
fn d7_unknown_due_filter_drops_undated_tasks_as_ios_does() {
    let f = load();
    let mut seen = 0;
    for case in disputed(&f, "D7") {
        seen += 1;
        assert_eq!(answer(&f, case), false, "{}", case["id"]);
    }
    assert!(seen > 0);
}

/// D34: on iOS a timed task due earlier today is not overdue until its day has passed; web calls
/// it overdue the moment its time does.
#[test]
fn d34_a_timed_task_due_earlier_today_is_not_overdue_as_on_ios() {
    let f = load();
    let mut seen = 0;
    for case in disputed(&f, "D34") {
        seen += 1;
        assert_eq!(answer(&f, case), false, "{}", case["id"]);
    }
    assert!(seen > 0);
}

/// D35: iOS does not read `tomorrow`, `this_calendar_week` or `this_calendar_month`; like any
/// value it does not know, they keep every dated task and drop undated ones (D7).
#[test]
fn d35_web_only_windows_read_as_unknown_values_as_on_ios() {
    let f = load();
    let mut seen = 0;
    for case in disputed(&f, "D35") {
        seen += 1;
        let dated = f.due_tasks[case["task"].as_str().unwrap()]
            .due_date_time
            .is_some();
        assert_eq!(answer(&f, case), dated, "{}", case["id"]);
    }
    assert!(seen > 0);
}

/// D36: "since the 31st" on 9 March reaches back to the last day February has, as iOS's
/// `Calendar` arithmetic does; web rolls on into 3 March.
#[test]
fn d36_since_a_day_last_month_lacks_clamps_as_on_ios() {
    let f = load();
    let shown = |id: &str| {
        let case = disputed(&f, "D36")
            .find(|c| c["id"] == id)
            .unwrap_or_else(|| panic!("{id} is disputed"));
        answer(&f, case)
    };
    assert_eq!(
        shown("completion/2026-03-09/since-31st/default/done-feb-28-noon"),
        true
    );
    assert_eq!(
        shown("completion/2026-03-09/since-31st/default/done-mar-2-noon"),
        true
    );
    assert_eq!(
        shown("completion/2026-10-09/since-31st/default/done-sep-30-noon"),
        true
    );
}

/// D33: iOS's sort orders (`sortTasksByListSetting`).
#[test]
fn d33_sort_orders_are_ios() {
    let f = load();
    let order = |sort: &str| {
        let case = disputed(&f, "D33")
            .find(|c| c["sortBy"] == sort)
            .unwrap_or_else(|| panic!("sort {sort} is disputed"));
        answer(&f, case)
    };
    let auto = ["s3", "s2", "s5", "s4", "s9", "s1", "s6", "s8", "s7"];
    // Completed sink; then priority, then due date.
    assert_eq!(order("priority"), Value::from(auto.to_vec()));
    // By due date (ties by priority), undated after, completed last.
    assert_eq!(
        order("when"),
        Value::from(vec!["s4", "s3", "s9", "s2", "s5", "s1", "s6", "s8", "s7"])
    );
    // Orders iOS does not have read as auto.
    for sort in ["assignee", "completed", "incomplete"] {
        assert_eq!(order(sort), Value::from(auto.to_vec()), "{sort}");
    }
    // Newest first.
    assert_eq!(
        order("createdAt"),
        Value::from(vec!["s9", "s8", "s7", "s6", "s5", "s4", "s3", "s2", "s1"])
    );
}
