//! A hand-arranged order reconciles, and draws, as astrid-web's does.
//!
//! `contracts/fixtures/manual-order.json` is generated by running `sanitizeManualOrder`
//! (`lib/list-manual-order.ts`) and the "manual" sort (`lib/task-sort.ts`) over a case table.
//! Disputed cases — tasks an arrangement does not name, D33 — must still disagree with web,
//! and the core answers them as iOS does: newest first.

mod common;

use astrid_rules::filters::sort_by_setting;
use astrid_rules::manual_order::reconcile;
use astrid_rules::model::Task;
use serde_json::Value;

const FIXTURE: &str = include_str!("../../../contracts/fixtures/manual-order.json");

fn strings(value: &Value) -> Vec<String> {
    value
        .as_array()
        .expect("an array")
        .iter()
        .map(|v| v.as_str().expect("a string").to_string())
        .collect()
}

fn answer(case: &Value) -> Vec<String> {
    if case["id"].as_str().unwrap().starts_with("reconcile/") {
        reconcile(
            &strings(&case["requested"]),
            &strings(&case["inListByCreation"]),
        )
    } else {
        let mut shown: Vec<Task> =
            serde_json::from_value(case["tasks"].clone()).expect("tasks decode");
        let order = strings(&case["manualOrder"]);
        sort_by_setting(&mut shown, Some("manual"), Some(&order));
        shown.into_iter().map(|t| t.id).collect()
    }
}

fn web(case: &Value) -> Vec<String> {
    strings(if case["stored"].is_array() {
        &case["stored"]
    } else {
        &case["shown"]
    })
}

#[test]
fn every_undisputed_case_answers_as_web_does() {
    let fixture: Value = serde_json::from_str(FIXTURE).expect("the fixture parses");
    let cases = fixture["cases"].as_array().unwrap();
    assert!(cases.len() >= 14);
    let failures: Vec<String> = cases
        .iter()
        .filter_map(|case| {
            let ours = answer(case);
            (ours != web(case))
                .then(|| format!("{}: web {:?}, core {ours:?}", case["id"], web(case)))
        })
        .collect();
    common::no_failures("manual-order.json", &failures);
}

/// D33: a task the arrangement does not name, and a list with no arrangement, come newest
/// first on iOS (`sortTasksByListSetting`, "manual") and here; web puts them oldest first.
#[test]
fn d33_disputed_cases_follow_ios() {
    let fixture: Value = serde_json::from_str(FIXTURE).expect("the fixture parses");
    let answered: Vec<common::Answered> = fixture["disputed"]
        .as_array()
        .unwrap()
        .iter()
        .map(|case| common::Answered {
            entry: case["entry"].as_str().unwrap().to_string(),
            id: case["id"].as_str().unwrap().to_string(),
            agrees_with_web: answer(case) == web(case),
        })
        .collect();
    common::each_dispute_still_disagrees(
        "manual-order.json",
        &common::declared(&fixture["disputes"]),
        &answered,
    );

    let by_id = |id: &str| {
        fixture["disputed"]
            .as_array()
            .unwrap()
            .iter()
            .find(|c| c["id"] == id)
            .unwrap_or_else(|| panic!("{id} is disputed"))
            .clone()
    };
    // Arranged d, b lead; the rest newest first.
    assert_eq!(
        answer(&by_id("display/unarranged-tasks")),
        ["d", "b", "e", "c", "a"]
    );
    assert_eq!(
        answer(&by_id("display/nothing-arranged")),
        ["e", "d", "c", "b", "a"]
    );
}
