//! A description, comment or chat message reads as it does on the web.
//!
//! `contracts/fixtures/markdown.json` is generated by running `renderMarkdownWithLinks`
//! (`lib/markdown.ts`: `marked`, GFM, `breaks: true`, then DOMPurify) in a jsdom window and
//! reading the HTML back into this crate's blocks and runs — the level the contract really is,
//! since web draws HTML and a native shell draws runs. How the HTML is read is written down in
//! the driver (`contracts/drivers/markdown.mjs`). Each case is rendered here and compared as JSON.
//!
//! The two parsers are different programs (`marked` and pulldown-cmark), so the disputed cases
//! are where they genuinely read the same text differently; D38 in `docs/CONTRACTS.md` lists
//! them and says which reading this crate keeps.

mod common;

use astrid_rules::identifier::LinkContext;
use astrid_rules::markdown::{render, render_with_identifiers};
use serde_json::Value;

const FIXTURE: &str = include_str!("../../../contracts/fixtures/markdown.json");

fn strings(value: &Value) -> Vec<String> {
    value
        .as_array()
        .map(|a| a.iter().map(|v| v.as_str().unwrap().to_string()).collect())
        .unwrap_or_default()
}

fn ours(case: &Value) -> Value {
    let text = case["text"].as_str().unwrap();
    let blocks = match case["context"].as_object() {
        Some(context) => render_with_identifiers(
            text,
            &LinkContext {
                project_key: context
                    .get("projectKey")
                    .and_then(Value::as_str)
                    .map(str::to_string),
                keys: strings(&context["keys"]),
                hidden: context.get("hidden").map(strings).unwrap_or_default(),
            },
        ),
        None => render(text),
    };
    serde_json::to_value(blocks).expect("blocks serialise")
}

#[test]
fn every_undisputed_text_renders_as_web_renders_it() {
    let fixture: Value = serde_json::from_str(FIXTURE).expect("the fixture parses");
    let cases = fixture["cases"].as_array().unwrap();
    assert!(cases.len() >= 60);
    let failures: Vec<String> = cases
        .iter()
        .filter_map(|case| {
            let ours = ours(case);
            (ours != case["blocks"]).then(|| {
                format!(
                    "{} {:?}\n   web:  {}\n   core: {ours}",
                    case["id"], case["text"], case["blocks"]
                )
            })
        })
        .collect();
    common::no_failures("markdown.json", &failures);
}

#[test]
fn each_disputed_entry_still_disagrees_with_web() {
    let fixture: Value = serde_json::from_str(FIXTURE).expect("the fixture parses");
    let answered: Vec<common::Answered> = fixture["disputed"]
        .as_array()
        .unwrap()
        .iter()
        .map(|case| common::Answered {
            entry: case["entry"].as_str().unwrap().to_string(),
            id: case["id"].as_str().unwrap().to_string(),
            agrees_with_web: ours(case) == case["blocks"],
        })
        .collect();
    common::each_dispute_still_disagrees(
        "markdown.json",
        &common::declared(&fixture["disputes"]),
        &answered,
    );
}
