//! Replays `contracts/fixtures/permissions.json` — generated by running astrid-web's own
//! `lib/list-permissions.ts` — against this crate's port.
//!
//! Permissions are the contract with the sharpest failure mode in either direction. Grant too much
//! and the UI offers a control that 403s, or worse, shows someone a list they should not see. Grant
//! too little and a collaborator silently loses the ability to do their job with no error to
//! explain it. Neither shows up in a unit test written from the same misunderstanding as the
//! implementation, which is why the answers here come from web rather than from me.
//!
//! The fixture includes the server-only inputs — the list's project (owner, members, and the
//! status-list cascade through sibling lists) and the legacy `admins` / `members` arrays — because
//! astrid-web's server decides through this crate with them loaded (AWTD-1061). A client never
//! sends them; `docs/CONTRACTS.md` §5 says what that still costs a client.

use astrid_rules::permissions::{
    can_delete_list, can_edit_task, can_edit_tasks, can_manage_list, can_manage_members,
    can_view_list, has_explicit_list_role, role_in_list, ListAccess, ListRole,
};
use serde::Deserialize;

const FIXTURE: &str = include_str!("../../../contracts/fixtures/permissions.json");

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Fixture {
    user_id: String,
    own_task_creator_id: String,
    others_task_creator_id: String,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    list: ListAccess,
    expected: Expected,
}

impl Case {
    fn is_server_only(&self) -> bool {
        self.list.project.is_some() || self.list.admins.is_some() || self.list.members.is_some()
    }
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Expected {
    role: Option<ListRole>,
    can_view_list: bool,
    can_edit_tasks: bool,
    can_edit_own_task: bool,
    can_edit_others_task: bool,
    has_explicit_list_role: bool,
    can_manage_list: bool,
    can_manage_members: bool,
    can_delete_list: bool,
}

/// Removes one server-only input from a list, to show that input was what granted the role.
type Strip = fn(&mut ListAccess);

fn fixture() -> Fixture {
    serde_json::from_str(FIXTURE).expect("permissions fixture parses")
}

#[test]
fn roles_match_web() {
    let f = fixture();
    for case in &f.cases {
        assert_eq!(
            role_in_list(&f.user_id, &case.list),
            case.expected.role,
            "role: {}",
            case.name
        );
    }
}

#[test]
fn predicates_match_web() {
    let f = fixture();
    for case in &f.cases {
        let e = &case.expected;
        let list = &case.list;
        let user = f.user_id.as_str();

        assert_eq!(
            can_view_list(user, list),
            e.can_view_list,
            "view: {}",
            case.name
        );
        assert_eq!(
            can_edit_tasks(user, list),
            e.can_edit_tasks,
            "edit tasks: {}",
            case.name
        );
        assert_eq!(
            has_explicit_list_role(user, list),
            e.has_explicit_list_role,
            "explicit role: {}",
            case.name
        );
        assert_eq!(
            can_manage_list(user, list),
            e.can_manage_list,
            "manage list: {}",
            case.name
        );
        assert_eq!(
            can_manage_members(user, list),
            e.can_manage_members,
            "manage members: {}",
            case.name
        );
        assert_eq!(
            can_delete_list(user, list),
            e.can_delete_list,
            "delete list: {}",
            case.name
        );
    }
}

/// Split from the rest because authorship changes the answer on exactly one kind of list, and a
/// single assertion would let that difference pass unnoticed.
#[test]
fn task_editing_respects_authorship_the_way_web_does() {
    let f = fixture();
    for case in &f.cases {
        assert_eq!(
            can_edit_task(&f.user_id, Some(&f.own_task_creator_id), &case.list),
            case.expected.can_edit_own_task,
            "own task: {}",
            case.name
        );
        assert_eq!(
            can_edit_task(&f.user_id, Some(&f.others_task_creator_id), &case.list),
            case.expected.can_edit_others_task,
            "someone else's task: {}",
            case.name
        );
    }
}

/// The fixture is only worth trusting if it actually covers the branches. A case list that quietly
/// lost its public-collaborative rows would still pass every assertion above.
#[test]
fn the_fixture_still_covers_the_branches_that_matter() {
    let f = fixture();

    let roles: Vec<Option<ListRole>> = f.cases.iter().map(|c| c.expected.role).collect();
    for expected in [
        Some(ListRole::Owner),
        Some(ListRole::Admin),
        Some(ListRole::Member),
        Some(ListRole::Viewer),
        None,
    ] {
        assert!(
            roles.contains(&expected),
            "fixture no longer covers role {expected:?}"
        );
    }

    // The server-only branches (AWTD-1061). Each must be the thing granting the role somewhere, or
    // the core could ignore that input and still pass.
    let without = |case: &Case, strip: fn(&mut ListAccess)| {
        let mut list = case.list.clone();
        strip(&mut list);
        role_in_list(&f.user_id, &list)
    };
    let branches: [(&str, Strip); 4] = [
        ("legacy admins", |l| l.admins = None),
        ("legacy members", |l| l.members = None),
        ("project", |l| l.project = None),
        ("status-list cascade", |l| l.list_type = None),
    ];
    for (branch, strip) in branches {
        assert!(
            f.cases
                .iter()
                .filter(|c| c.is_server_only())
                .any(|c| c.expected.role.is_some() && without(c, strip) != c.expected.role),
            "fixture no longer covers a role granted by the {branch} branch"
        );
    }

    // The one place authorship decides the answer: a public collaborative list, where a viewer may
    // edit their own task and a member may NOT edit someone else's.
    assert!(
        f.cases
            .iter()
            .any(|c| c.expected.can_edit_own_task && !c.expected.can_edit_others_task),
        "fixture no longer covers a list where editing depends on who wrote the task"
    );
}
