//! A snooze comes back when astrid-web's does.
//!
//! `contracts/fixtures/reminders.json` is generated by running `snoozeReminder`
//! (`lib/reminder-snooze.ts`) over scripted sequences against an in-memory reminder queue: what it
//! schedules is now plus the minutes, which is `reminders::snooze_until`. The bounds are the v1
//! route's. Web's sixth-snooze refusal is D37's and disputed: iOS, and so the core, has no limit.

mod common;

use astrid_rules::model::date;
use astrid_rules::reminders::{snooze_until, NOTIFICATION_SNOOZE_MINUTES, SNOOZE_CHOICES};
use serde_json::Value;

const FIXTURE: &str = include_str!("../../../contracts/fixtures/reminders.json");

fn fixture() -> Value {
    serde_json::from_str(FIXTURE).expect("the fixture parses")
}

#[test]
fn every_snooze_comes_back_when_webs_does() {
    let fixture = fixture();
    let cases = fixture["cases"].as_array().unwrap();
    assert!(cases.len() >= 9);
    let mut failures = Vec::new();
    for case in cases {
        assert_eq!(
            case["ok"], true,
            "{}: an undisputed snooze is accepted",
            case["id"]
        );
        let now = date::parse(case["now"].as_str().unwrap()).expect("now");
        let web = date::parse(case["scheduledFor"].as_str().unwrap()).expect("scheduledFor");
        let ours = snooze_until(now, case["minutes"].as_i64().unwrap());
        if ours != web {
            failures.push(format!("{}: web {web}, core {ours}", case["id"]));
        }
    }
    common::no_failures("reminders.json", &failures);
}

/// Every snooze this crate offers is one the server accepts. A choice outside the v1 route's
/// range would be refused on the wire the moment a client sent it there.
#[test]
fn every_snooze_choice_is_within_the_servers_range() {
    let fixture = fixture();
    let min = fixture["minutes"]["min"].as_i64().unwrap();
    let max = fixture["minutes"]["max"].as_i64().unwrap();
    for minutes in SNOOZE_CHOICES
        .iter()
        .copied()
        .chain([NOTIFICATION_SNOOZE_MINUTES])
    {
        assert!(
            (min..=max).contains(&minutes),
            "{minutes} minutes is outside {min}..={max}"
        );
    }
}

/// D37: web refuses a sixth snooze of one reminder; iOS snoozes as often as asked, and so does
/// this crate — the sixth comes back at now plus the minutes like the others.
#[test]
fn d37_a_sixth_snooze_is_not_refused_here() {
    let fixture = fixture();
    let answered: Vec<common::Answered> = fixture["disputed"]
        .as_array()
        .unwrap()
        .iter()
        .map(|case| {
            let now = date::parse(case["now"].as_str().unwrap()).expect("now");
            let ours = snooze_until(now, case["minutes"].as_i64().unwrap());
            assert!(ours > now, "{}: the core snoozes", case["id"]);
            common::Answered {
                entry: case["entry"].as_str().unwrap().to_string(),
                id: case["id"].as_str().unwrap().to_string(),
                // Web refused; the core answers with a time. They agree only if web stops refusing.
                agrees_with_web: case["ok"] == true,
            }
        })
        .collect();
    common::each_dispute_still_disagrees(
        "reminders.json",
        &common::declared(&fixture["disputes"]),
        &answered,
    );
}
